version: "3"
services:
  snake-srv:
    container_name: snake-srv
    build:
      context: snake-srv/.
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  
  mongo-db:
    container_name: snake-db
    image: mongo:latest
    # volumes:
    #   - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
    #   - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
    #   - ./.docker/mongodb/data/db/:/data/db/
    #   - ./.docker/mongodb/data/db/:/data/configdb/

  snake-ui:
    container_name: snake-ui
    build:
      context: snake-ui/.
      dockerfile: Dockerfile
      args:
        host: localhost
    ports:
      - 8081:80
